In [1]:
import torch

<img src="graph1.png">

In [11]:
x = torch.randn(3, requires_grad=True)
print(x)

y = x + 2
print(y)

z = y*y*2
#z = z.mean()
print(z)
v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
z.backward(v) # dz/dx
print(x.grad)


tensor([ 0.6309, -0.3056,  0.6232], requires_grad=True)
tensor([2.6309, 1.6944, 2.6232], grad_fn=<AddBackward0>)
tensor([13.8436,  5.7421, 13.7623], grad_fn=<MulBackward0>)
tensor([1.0524, 6.7777, 0.0105])


In [16]:
x = torch.randn(3, requires_grad=True)
print(x)

x.requires_grad_(False)
y = x.detach()
print(x)
print(y)
with torch.no_grad():
    y = x + 2
    print(y)

tensor([-1.7561,  0.0779, -0.4663], requires_grad=True)
tensor([-1.7561,  0.0779, -0.4663])
tensor([-1.7561,  0.0779, -0.4663])
tensor([0.2439, 2.0779, 1.5337])


$\vec{x} = \begin{bmatrix} 1 & 1 & 1 & 1 \end{bmatrix}^T$ \
$ z = 3 \cdot \vec{1} \cdot \vec{x} = 3x_1 + 3x_2 + 3x_3 + 3x_4$ \
$\frac{\partial z}{\partial \vec{x}} = \begin{bmatrix}
\frac{\partial z}{\partial x_1} & 
\frac{\partial z}{\partial x_2} &
\frac{\partial z}{\partial x_3} &
\frac{\partial z}{\partial x_4} 
\end{bmatrix}$

In [22]:
weights = torch.ones(4, requires_grad=True)
print(weights)
print()

for epoch in range(3):
    model_output = (weights*3).sum()
    print(model_output)
    
    model_output.backward()
    
    print(weights.grad)

    weights.grad.zero_() # IMPORTANT

tensor([1., 1., 1., 1.], requires_grad=True)

tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])


In [24]:
weights = torch.ones(4, requires_grad=True)


TypeError: params argument given to the optimizer should be an iterable of Tensors or dicts, but got torch.FloatTensor