In [2]:
import torch

print (torch.__version__)

1.11.0


In [5]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

print(x.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [7]:
# y = x + 2
y = x + 2
print(y)

print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [8]:
z = y * y * 3
out = z.mean()

print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [9]:
a = torch.randn(2, 2)
print(a)

tensor([[-0.4234, -0.6888],
        [ 0.8577, -0.7736]])


In [10]:
a = ((a * 3) / (a-1))
print(a)
print(a.requires_grad)

tensor([[  0.8924,   1.2236],
        [-18.0800,   1.3085]])
False


In [12]:
a.requires_grad_(True)

tensor([[  0.8924,   1.2236],
        [-18.0800,   1.3085]], requires_grad=True)

In [13]:
print(a.requires_grad)

True


In [14]:
b = (a * a).sum()
print(b)
print(b.requires_grad)

tensor(330.8907, grad_fn=<SumBackward0>)
True


$x = \begin{bmatrix} 1 & 1 \\ 1 & 1 \end{bmatrix} $ \
$y = x + 2 = \begin{bmatrix} 3 & 3 \\ 3 & 3 \end{bmatrix} $ \
$ z = y * y * 3 $ \
$ \text{out} = \text{mean } z$

In [16]:
print(out)
y.retain_grad()
z.retain_grad()
out.backward()

print(x.grad)
print(y.grad)
print(z.grad)
print(z.is_leaf)



tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])
False
