In [3]:
%matplotlib inline

from __future__ import print_function

import torch
torch.__version__

'1.11.0'

초기화 되지 않은 5X3 행렬

In [4]:
x = torch.empty(5, 4)
print(x)

tensor([[-1.7742e-21,  4.5846e-41,  1.4135e-15,  3.0798e-41],
        [ 4.4842e-44,  0.0000e+00,  1.5695e-43,  0.0000e+00],
        [ 1.4172e-15,  3.0798e-41,  0.0000e+00,  0.0000e+00],
        [ 1.4132e-15,  3.0798e-41,  6.5438e-16,  3.0798e-41],
        [-3.0823e-26,  4.5845e-41,  1.4013e-45,  0.0000e+00]])


무작위로 초기화된 행렬 생성

In [5]:
x = torch.randn(5, 3)
print(x)
x = torch.rand(5, 3)
print(x)

tensor([[ 0.0906,  0.4170,  0.5249],
        [ 0.9487, -1.8633,  0.0686],
        [ 0.1454,  0.9635, -1.1276],
        [-0.7705, -0.2787, -0.7838],
        [ 0.7154, -1.1057,  0.3650]])
tensor([[0.2612, 0.5654, 0.8823],
        [0.1032, 0.4935, 0.7090],
        [0.3105, 0.4019, 0.2993],
        [0.0675, 0.3846, 0.5816],
        [0.0765, 0.1820, 0.6442]])


dtype = long, 0 matrix

In [2]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [3]:
x = torch.ones(5, 3, dtype=torch.long)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


데이터로부터 tensor를 직접 생성

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


존재하는 tensor를 바탕으로 tensor 생성

In [8]:
x = torch.ones(5, 4, dtype=torch.double)
x = torch.randn_like(x, dtype=torch.float)
print(x)
print(x.size())
print(x.shape)

tensor([[-1.6573, -0.8755, -1.0433, -0.3262],
        [-0.4608, -1.1088,  0.1856,  0.7608],
        [ 1.7064, -0.4966,  1.4535, -0.2245],
        [ 0.3101, -1.6569,  1.1901,  0.9657],
        [ 1.5073, -0.1702, -1.3501,  0.1850]])
torch.Size([5, 4])
torch.Size([5, 4])


Addition 

In [10]:
x = torch.randn(5, 3, dtype=torch.float)
y = torch.randn(5, 3, dtype=torch.float)
print(x + y)

tensor([[-0.9934, -1.4195, -0.5691],
        [-2.5662, -2.3345,  0.2224],
        [ 0.3225, -0.0514, -0.0552],
        [-2.7692, -0.6193,  0.1802],
        [ 1.8278,  2.5970, -1.0278]])


In [12]:
print(torch.add(x, y))

tensor([[-0.9934, -1.4195, -0.5691],
        [-2.5662, -2.3345,  0.2224],
        [ 0.3225, -0.0514, -0.0552],
        [-2.7692, -0.6193,  0.1802],
        [ 1.8278,  2.5970, -1.0278]])


결과 tensor를 인자로 제공

In [15]:
result = torch.empty(5, 3)
print(result)

torch.add(x, y, out=result)
print(result)

tensor([[-6.4237e+04,  4.5859e-41, -8.3458e-07],
        [ 3.0645e-41,  1.4013e-45,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [-8.3967e-07,  3.0645e-41, -3.8912e-07]])
tensor([[-0.9934, -1.4195, -0.5691],
        [-2.5662, -2.3345,  0.2224],
        [ 0.3225, -0.0514, -0.0552],
        [-2.7692, -0.6193,  0.1802],
        [ 1.8278,  2.5970, -1.0278]])


in place

In [17]:
print(y)
y.add_(x)
print(y)

tensor([[-0.9934, -1.4195, -0.5691],
        [-2.5662, -2.3345,  0.2224],
        [ 0.3225, -0.0514, -0.0552],
        [-2.7692, -0.6193,  0.1802],
        [ 1.8278,  2.5970, -1.0278]])
tensor([[-1.7836, -1.6803, -0.6461],
        [-3.6684, -4.0817, -0.5140],
        [ 0.6371, -0.1803, -0.4017],
        [-5.4994, -0.6135,  0.3468],
        [ 3.2573,  3.1384, -1.0146]])


Note that in-place use `_` as a prefix

In [24]:
print(x)
print(x[:, 1])

tensor([[-0.7902, -0.2608, -0.0769],
        [-1.1021, -1.7472, -0.7364],
        [ 0.3146, -0.1290, -0.3465],
        [-2.7301,  0.0058,  0.1666],
        [ 1.4295,  0.5414,  0.0132]])
tensor([-0.2608, -1.7472, -0.1290,  0.0058,  0.5414])


### Resize / Reshape

In [26]:
x = torch.randn(4, 4)
print(x)

y = x.view(16)
z = y.view(-1, 2) # the size -1 is inferred from other dimension
print(y)
print(z)
print(y.size(), z.size())

tensor([[-0.6744, -1.0493, -0.9698,  2.1672],
        [ 1.0424,  0.1161, -0.2055, -1.4820],
        [-0.8757, -0.2865,  0.9476, -2.0753],
        [ 1.2477,  0.0060,  0.2987,  0.6485]])
tensor([-0.6744, -1.0493, -0.9698,  2.1672,  1.0424,  0.1161, -0.2055, -1.4820,
        -0.8757, -0.2865,  0.9476, -2.0753,  1.2477,  0.0060,  0.2987,  0.6485])
tensor([[-0.6744, -1.0493],
        [-0.9698,  2.1672],
        [ 1.0424,  0.1161],
        [-0.2055, -1.4820],
        [-0.8757, -0.2865],
        [ 0.9476, -2.0753],
        [ 1.2477,  0.0060],
        [ 0.2987,  0.6485]])
torch.Size([16]) torch.Size([8, 2])


만약 tensor에 하나의 값만 존재한다면 `item()`를 통해 숫자 값을 얻을 수 있다.

In [27]:
x = torch.randn(1)
print(x)
print(type(x), type(x.item()))
print(x.item())


tensor([-0.4667])
<class 'torch.Tensor'> <class 'float'>
-0.46669885516166687


## Numpy 변환
CPU 상의 Torch tensor와 Numpy배열 공간은 저장 공간을 공유하기 때문에 하나를 변경하면 다른 하나도 변경됩니다.
- Torch Tensor를 NumPy배열로 변환하기

In [28]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [29]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [30]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [32]:
temp = a.clone()
temp_numpy = temp.numpy()

a.add_(1)
print(a)
print(temp_numpy)

tensor([3., 3., 3., 3., 3.])
[2. 2. 2. 2. 2.]


## CUDA Tensors
.to 메소드를 사용하여 Tensor를 어떠한 장치로도 옮길 수 있다.

In [35]:
import torch

x = torch.rand(4,4)

if torch.cuda.is_available():
    device = "cuda:0"
    y = torch.ones_like(x, device=device)
    print(y)
    
    x = x.to(device) # x -> gpu
    z = x + y # z -> gpu
    print(z)
    print(z.to("cpu", torch.double)) # z -> cpu

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')
tensor([[1.5241, 1.3103, 1.2818, 1.2985],
        [1.5337, 1.3225, 1.1908, 1.4600],
        [1.3852, 1.0130, 1.1681, 1.3172],
        [1.7379, 1.4716, 1.5377, 1.6011]], device='cuda:0')
tensor([[1.5241, 1.3103, 1.2818, 1.2985],
        [1.5337, 1.3225, 1.1908, 1.4600],
        [1.3852, 1.0130, 1.1681, 1.3172],
        [1.7379, 1.4716, 1.5377, 1.6011]], dtype=torch.float64)


In [37]:
x = x.cuda()
print(x)

tensor([[0.5241, 0.3103, 0.2818, 0.2985],
        [0.5337, 0.3225, 0.1908, 0.4600],
        [0.3852, 0.0130, 0.1681, 0.3172],
        [0.7379, 0.4716, 0.5377, 0.6011]], device='cuda:0')
