In [53]:
import torch
import numpy as np

In [10]:
x = torch.empty(2, 2, 2, 3)

print(x)

tensor([[[[-3.4504e+07,  3.0823e-41, -3.4299e+07],
          [ 3.0823e-41,  1.5695e-43,  0.0000e+00]],

         [[ 1.5695e-43,  0.0000e+00, -3.4504e+07],
          [ 3.0823e-41,  3.4483e+07,  3.0823e-41]]],


        [[[ 0.0000e+00,  0.0000e+00,  4.6243e-44],
          [ 0.0000e+00,  3.4299e+07,  3.0823e-41]],

         [[ 3.9328e+07,  3.0823e-41,  2.0179e-43],
          [ 0.0000e+00,  1.1210e-43,  0.0000e+00]]]])


In [13]:
x = torch.rand(2, 2)
print(x)

tensor([[0.4113, 0.2533],
        [0.7020, 0.3234]])


In [16]:
x = torch.zeros(2, 2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [26]:
x = torch.ones(2, 2, dtype=torch.float64)
print(x.dtype)
print(x.size())

torch.float64
torch.Size([2, 2])


In [29]:
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


In [33]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

z = x + y
z = torch.add(x, y)
print(z)


tensor([[0.4232, 0.6649],
        [0.8437, 0.6594]])
tensor([[0.0202, 0.1829],
        [0.7034, 0.8463]])
tensor([[0.4435, 0.8478],
        [1.5471, 1.5056]])


In [36]:
x = torch.rand(2,2)
y = torch.rand(2,2)
y.add_(x)
print(y)


tensor([[0.9692, 1.7790],
        [0.4295, 1.8063]])


In [41]:
x = torch.rand(2,2)
y = torch.rand(2,2)

z = x * y
z = torch.mul(x, y)
print(z)



tensor([[0.0778, 0.4906],
        [0.0471, 0.1646]])


In [48]:
x = torch.rand(5, 3)
print(x)

print(x[:, 0])
print(x[1, :])
print(x[1, 1])
print(x[1, 1].item())

tensor([[0.7024, 0.0559, 0.8467],
        [0.8419, 0.4670, 0.3793],
        [0.6873, 0.4338, 0.7789],
        [0.4179, 0.5237, 0.3858],
        [0.3129, 0.4786, 0.5634]])
tensor([0.7024, 0.8419, 0.6873, 0.4179, 0.3129])
tensor([0.8419, 0.4670, 0.3793])
tensor(0.4670)
0.4669743776321411


In [52]:
x = torch.rand(4,4)
print(x)

y = x.view(16)
print(y)

y = x.view(-1, 8)
print(y)

tensor([[0.4076, 0.7848, 0.5592, 0.9244],
        [0.1129, 0.4698, 0.7930, 0.8686],
        [0.6667, 0.1331, 0.9652, 0.3915],
        [0.7402, 0.7069, 0.6927, 0.4655]])
tensor([0.4076, 0.7848, 0.5592, 0.9244, 0.1129, 0.4698, 0.7930, 0.8686, 0.6667,
        0.1331, 0.9652, 0.3915, 0.7402, 0.7069, 0.6927, 0.4655])
tensor([[0.4076, 0.7848, 0.5592, 0.9244, 0.1129, 0.4698, 0.7930, 0.8686],
        [0.6667, 0.1331, 0.9652, 0.3915, 0.7402, 0.7069, 0.6927, 0.4655]])


In [58]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(type(b))

a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [61]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

a += 1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [65]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y # gpu
    z = z.to("cpu")
print(z)


tensor([2., 2., 2., 2., 2.])
